### ISSUE TITLE
Exporting issues

### ISSUE THREAD

**Issue by jorisBarkema** [jorisBarkema/svelte-burger-menu#6]
I tried to create a little Divider component to use in the menu, but when trying to export it as part of the package everything broke. I reset everything so that it should work again, but just cannot get node and typescript to work properly on my laptop. @11reed could you verify that 2.0.4 still works properly?

**Comment by 11reed** [comment]
The changes need to be published to npm. That is why it isn't working. I don't have privileges to do that so that is something that you or someone that has them needs to do. If you notice, when you install via npm, it is still version 1.0.5. All of the .d.ts files needed were generated in the latest version.

**Comment by 11reed** [comment]
Read #7 . I have included a lot of details regarding your question in the comment.

**Comment by 11reed** [comment]
Alright, you can ignore #7 for now. I made a lot of big changes and decided to go the route of using my own type declarations inside, as opposed to generating them in the bundle.

**Comment by 11reed** [comment]
Closed both #7 and #8. Need to work on this tomorrow.

**Comment by 11reed** [comment]
Ignore both #7 and #8. The issue is as simple as removing types from BurgerButton and SideMenu. Basically, since BurgerMenu is the only exported component, the types only need to live inside there. I started working on a new typescript/sveltekit library earlier and it's as simple as that. I will do this tomorrow once I've slept, or you can if you want, since there's only a few lines needed to remove. It should work perfectly when those changes are made.
